env:
    CIRRUS_CLONE_DEPTH: 1
    BUILD_HOSTNAME: "CirrusCI"
    CIRRUS_WORKING_DIR: "/tmp/ci"
    GH_USERNAME: "ENCRYPTED[a50e7c9a0ed7fd7f86ff677cf829f15d747fd7c9b789dc3975769c6d92879889ace603f0569a12827c51d56369e38b7a]"
    GH_EMAIL: "ENCRYPTED[1cc52fd3430a4af9aabb43f20822c6651b5a855a638afd62a7319796a949d84c2caeafc55eaf6fca56d9f8589bc334a9]"
    GH_TOKEN: "ENCRYPTED[3e7af2cc1dcb46f34f4d96479b7ee79dc06cdd1dd9b62592c25b1c1f99580437c4823434e00983ef475fa2605d135a85]"
    GH_STORE: "ENCRYPTED[5d072e5293bad1d98904250e9b4a60e4e5913e64813e189e51ff24e75e378502872f3a9cc44e278f5ef80255f79cfe18]"
    BRANCH_NAME: "dec"
    ANDROID_R: 

task:
  name: Merge android frameworks base
  container:
    image: dopaemon/focal:latest
    cpu: 4
    memory: 8G

  setup_package_script:
    - sudo apt-get install sshpass -y

  setup_git_script:
    - git config --global user.name $GH_USERNAME
    - git config --global user.email $GH_EMAIL
    - git config --global credential.helper store
    - sshpass -p $GH_TOKEN git clone $GH_STORE ./.store

  clone_repo_script:
    - git clone -b $BRANCH_NAME --single-branch https://github.com/CherishOS/android_frameworks_base.git ./android_frameworks_base

  merge_script:
    - cd ./android_frameworks_base
    - git fetch https://github.com/GrapheneOS/platform_frameworks_base.git -t 14
    - git merge --no-edit FETCH_HEAD

  push_repo:
    - cd ./android_frameworks_base
    - git push -u origin $BRANCH_NAME
